language: java
before_install:
  - pip install --user codecov
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov --file coverage/lcov.info --disable search
