language: java
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - "mvn cobertura:cobertura"
  - pip install codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://codecov.io/bash) -t e01e533a-2c04-479c-ad31-c61e6de62e52
